In [3]:
import pandas as pd

df = pd.read_excel("sales_data.xlsx")

In [4]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [5]:
df=df.drop_duplicates()

In [6]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [7]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')

In [8]:
df=df.dropna(subset=['Order_Date'])

In [9]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [11]:
df['Profit']=df['Sales'] - df['Cost']

In [12]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost  Profit
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118    4171
1        1002 2023-10-07     Aman   West   Laptop   8905   5593    3312
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959   20028
3        1004 2024-02-19    Rahul  South  Printer  49597  33892   15705
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468   20329
..        ...        ...      ...    ...      ...    ...    ...     ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931    5778
495      1496 2023-04-24    Kiran  North  Printer  23434  16388    7046
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970   13037
497      1498 2023-05-08     Aman   East   Tablet  19160  15636    3524
499      1500 2023-10-07    Vikas  North  Printer  34567  22426   12141

[482 rows x 8 columns]

In [14]:
df['Year']=df['Order_Date'].dt.year
df['Month']=df['Order_Date'].dt.month

In [15]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [16]:
df.to_csv('Sales_Data_Cleaned.csv',index=False)

In [17]:
import pandas as pd
from sqlalchemy import create_engine

In [19]:
df = pd.read_csv('Sales_Data_Cleaned.csv')

In [20]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,1/13/2023,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,10/7/2023,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,11/5/2023,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2/19/2024,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,1/26/2024,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,10/18/2023,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,4/24/2023,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,6/27/2023,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,5/8/2023,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,10/7/2023,Vikas,North,Printer,34567,22426,12141,2023,10

In [21]:
engine = create_engine('mysql+pymysql://root:password@localhost:3306/sales_db')

In [22]:
df.to_sql(name='sales_data',con=engine,if_exists='replace',index=False)

482